# Generated by Django 5.1.4 on 2025-01-04 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('account_amocrm', models.CharField(max_length=255, unique=True, verbose_name='Аккаунт amoCRM')),
                ('bearer_amocrm', models.TextField(verbose_name='Bearer amoCRM')),
                ('s2t_api_key', models.TextField(blank=True, null=True, verbose_name='API-ключ Speech2Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncomingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(verbose_name='Тело запроса')),
                ('domain', models.CharField(blank=True, max_length=255, verbose_name='Домен')),
                ('user_id', models.CharField(blank=True, max_length=255, verbose_name='ID пользователя')),
                ('note_id', models.CharField(blank=True, max_length=255, verbose_name='ID примечания')),
                ('audio_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='zapp.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Входящий запрос',
                'verbose_name_plural': 'Входящие запросы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='S2TRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='ID задачи в Speech2Text')),
                ('audio_link', models.URLField(verbose_name='Ссылка на аудиофайл')),
                ('raw_result_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на raw результат')),
                ('txt_result_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на txt результат')),
                ('json_result_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на json результат')),
                ('transcribed_text', models.TextField(blank=True, null=True, verbose_name='Транскрибированный текст')),
                ('status', models.CharField(default='pending', max_length=255, verbose_name='Статус задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('incoming_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_s2t_requests', to='zapp.incomingrequest', verbose_name='Связанный входящий запрос')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s2t_requests', to='zapp.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Запрос Speech2Text',
                'verbose_name_plural': 'Запросы Speech2Text',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='incomingrequest',
            name='s2t_requests',
            field=models.ManyToManyField(blank=True, to='zapp.s2trequest'),
        ),
    ]
