# Generated by Django 5.1.4 on 2025-01-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s2trequest',
            name='task_id',
            field=models.CharField(max_length=255, verbose_name='ID задачи в Speech2Text'),
        ),
    ]
