# Generated by Django 5.1.4 on 2025-01-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0002_alter_s2trequest_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='donkit_api_key',
            field=models.TextField(blank=True, null=True, verbose_name='API-ключ Donkit'),
        ),
    ]
