# Generated by Django 5.1.4 on 2025-01-07 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0003_organization_donkit_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='donkit_bearer_token',
            field=models.TextField(blank=True, null=True, verbose_name='Bearer-токен Donkit'),
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название промпта')),
                ('description', models.TextField(blank=True, verbose_name='Описание промпта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='zapp.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Промпт',
                'verbose_name_plural': 'Промпты',
                'ordering': ['-created_at'],
            },
        ),
    ]
