# Generated by Django 5.1.4 on 2025-01-08 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0004_organization_donkit_bearer_token_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonkitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255, verbose_name='ID чата Donkit')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('incoming_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donkit_requests', to='zapp.incomingrequest', verbose_name='Связанный входящий запрос')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donkit_requests', to='zapp.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Запрос Donkit',
                'verbose_name_plural': 'Запросы Donkit',
                'ordering': ['-created_at'],
            },
        ),
    ]
