# Generated by Django 5.1.4 on 2025-01-08 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0005_donkitrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='donkitrequest',
            name='status',
            field=models.CharField(default='pending', max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='donkitrequest',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='donkitrequest',
            name='incoming_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_donkit_requests', to='zapp.incomingrequest', verbose_name='Связанный входящий запрос'),
        ),
        migrations.AlterField(
            model_name='donkitrequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapp.organization', verbose_name='Организация'),
        ),
    ]
