# Generated by Django 5.1.4 on 2025-01-09 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0007_donkitrequest_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donkitrequest',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_donkit_requests', to='zapp.prompt', verbose_name='Используемый промпт'),
        ),
    ]
