# Generated by Django 5.1.4 on 2025-01-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0008_alter_donkitrequest_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название промпта'),
        ),
    ]
