# Generated by Django 5.1.4 on 2025-01-16 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0009_alter_prompt_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.BooleanField(default=False, verbose_name='Встреча')),
                ('questions', models.BooleanField(default=False, verbose_name='Вопросы')),
                ('positive', models.BooleanField(default=False, verbose_name='Добро')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('incoming_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='zapp.incomingrequest', verbose_name='Входящий запрос')),
            ],
            options={
                'verbose_name': 'Критерий',
                'verbose_name_plural': 'Критерии',
                'ordering': ['-created_at'],
            },
        ),
    ]
