# Generated by Django 5.1.4 on 2025-01-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0011_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingrequest',
            name='audio_duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
