# Generated by Django 5.1.4 on 2025-01-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0012_incomingrequest_audio_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='total_audio_duration',
            field=models.IntegerField(default=0),
        ),
    ]
