# Generated by Django 5.1.4 on 2025-03-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0013_organization_total_audio_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donkitrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запрос DeepSeekV3', 'verbose_name_plural': 'Запросы DeepSeekV3'},
        ),
        migrations.AddField(
            model_name='donkitrequest',
            name='tokens_used',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Токены'),
        ),
        migrations.AlterField(
            model_name='donkitrequest',
            name='chat_id',
            field=models.CharField(max_length=255, verbose_name='ID чата DeepSeekV3'),
        ),
    ]
