# Generated by Django 5.1.4 on 2025-03-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0014_alter_donkitrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Оценка'),
        ),
    ]
