# Generated by Django 5.1.4 on 2025-03-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0015_criteria_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingrequest',
            name='s2t_requests',
        ),
        migrations.AddField(
            model_name='incomingrequest',
            name='domain_b24',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Домен Bitrix24'),
        ),
        migrations.AddField(
            model_name='incomingrequest',
            name='source',
            field=models.CharField(choices=[('amoCRM', 'amoCRM'), ('Bitrix24', 'Bitrix24')], default='amoCRM', max_length=20, verbose_name='Источник запроса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomingrequest',
            name='user_id_b24',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID контакта Bitrix24'),
        ),
        migrations.AddField(
            model_name='organization',
            name='b24_admin_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID администратора Bitrix24'),
        ),
        migrations.AddField(
            model_name='organization',
            name='b24_api_comment',
            field=models.TextField(blank=True, null=True, verbose_name='API комментариев Bitrix24'),
        ),
        migrations.AddField(
            model_name='organization',
            name='b24_api_stat',
            field=models.TextField(blank=True, null=True, verbose_name='API статистики Bitrix24'),
        ),
        migrations.AddField(
            model_name='organization',
            name='b24_domain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Домен Bitrix24'),
        ),
        migrations.AlterField(
            model_name='incomingrequest',
            name='audio_duration',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Длительность аудио (сек)'),
        ),
        migrations.AlterField(
            model_name='incomingrequest',
            name='audio_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на аудиозапись'),
        ),
        migrations.AlterField(
            model_name='incomingrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления запроса'),
        ),
        migrations.AlterField(
            model_name='incomingrequest',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Домен amoCRM'),
        ),
        migrations.AlterField(
            model_name='incomingrequest',
            name='note_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID примечания'),
        ),
        migrations.AlterField(
            model_name='incomingrequest',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID пользователя amoCRM'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='donkit_api_key',
            field=models.TextField(blank=True, null=True, verbose_name='API Fireworks'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='s2t_api_key',
            field=models.TextField(blank=True, null=True, verbose_name='API Speech2Text'),
        ),
    ]
