# Generated by Django 5.1.4 on 2025-03-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0016_remove_incomingrequest_s2t_requests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingrequest',
            name='call_id_b24',
            field=models.CharField(blank=True, max_length=255, verbose_name='CALL_ID Bitrix24'),
        ),
    ]
