# Generated by Django 5.1.4 on 2025-03-14 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0017_incomingrequest_call_id_b24'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('needs_analysis', models.IntegerField(blank=True, null=True)),
                ('presentation', models.IntegerField(blank=True, null=True)),
                ('persuasion', models.IntegerField(blank=True, null=True)),
                ('follow_up', models.IntegerField(blank=True, null=True)),
                ('objections', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('incoming_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_steps', to='zapp.incomingrequest')),
            ],
            options={
                'verbose_name': 'Критерий 2.0',
                'verbose_name_plural': 'Критерии 2.0',
                'ordering': ['-created_at'],
            },
        ),
    ]
