# Generated by Django 5.1.4 on 2025-03-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0018_criteriasteps'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingrequest',
            name='crm_entity_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID CRM-сущности'),
        ),
        migrations.AddField(
            model_name='incomingrequest',
            name='crm_entity_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип CRM-сущности'),
        ),
    ]
