# Generated by Django 5.1.4 on 2025-03-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0020_alter_incomingrequest_audio_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingrequest',
            name='audio_link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на аудиозапись'),
        ),
        migrations.AlterField(
            model_name='s2trequest',
            name='audio_link',
            field=models.CharField(max_length=1000, verbose_name='Ссылка на аудиофайл'),
        ),
        migrations.AlterField(
            model_name='s2trequest',
            name='json_result_link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на json результат'),
        ),
        migrations.AlterField(
            model_name='s2trequest',
            name='raw_result_link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на raw результат'),
        ),
        migrations.AlterField(
            model_name='s2trequest',
            name='txt_result_link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на txt результат'),
        ),
    ]
