# Generated by Django 5.1.4 on 2025-03-19 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0021_alter_incomingrequest_audio_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingrequest',
            name='client_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон клиента'),
        ),
        migrations.CreateModel(
            name='DealStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_type', models.CharField(choices=[('amoCRM', 'amoCRM'), ('Bitrix24', 'Bitrix24')], max_length=20, verbose_name='Тип CRM')),
                ('deal_id_crm', models.CharField(max_length=255, verbose_name='ID сделки в CRM')),
                ('deal_type', models.CharField(choices=[('first', 'Первый контакт'), ('second', 'Повторное касание'), ('final', 'Закрытие сделки')], max_length=20, verbose_name='Тип сделки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_stages', to='zapp.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Этап сделки',
                'verbose_name_plural': 'Этапы сделок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='incomingrequest',
            name='deal_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_requests', to='zapp.dealstage', verbose_name='Этап сделки'),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id_crm', models.CharField(max_length=255, verbose_name='ID менеджера в CRM')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='zapp.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='incomingrequest',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_requests', to='zapp.manager', verbose_name='Менеджер'),
        ),
    ]
