# Generated by Django 5.1.4 on 2025-03-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0022_incomingrequest_client_phone_dealstage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='b24_api_leads',
            field=models.TextField(blank=True, null=True, verbose_name='API лидов Bitrix24'),
        ),
    ]
