# Generated by Django 5.1.4 on 2025-03-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0023_organization_b24_api_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='b24_api_lead_status',
            field=models.TextField(blank=True, null=True, verbose_name='API статуса лида Bitrix24'),
        ),
    ]
