# Generated by Django 5.1.4 on 2025-03-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0024_organization_b24_api_lead_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealstage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
        migrations.AddField(
            model_name='dealstage',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус сделки'),
        ),
    ]
