# Generated by Django 5.1.4 on 2025-03-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0025_alter_dealstage_options_dealstage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingrequest',
            name='temp_deal_stages',
            field=models.ManyToManyField(blank=True, related_name='temp_incoming_requests', to='zapp.dealstage', verbose_name='Временные этапы сделок'),
        ),
    ]
