# Generated by Django 5.1.4 on 2025-03-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0026_incomingrequest_temp_deal_stages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingrequest',
            name='deal_stage',
        ),
        migrations.RemoveField(
            model_name='incomingrequest',
            name='temp_deal_stages',
        ),
        migrations.AddField(
            model_name='incomingrequest',
            name='deal_stages',
            field=models.ManyToManyField(blank=True, related_name='incoming_requests', to='zapp.dealstage', verbose_name='Этапы сделок'),
        ),
    ]
