# Generated by Django 5.1.4 on 2025-03-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0027_remove_incomingrequest_deal_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='stats_type',
            field=models.IntegerField(choices=[(1, 'Старая статистика'), (2, 'Новая статистика')], default=2, verbose_name='Тип статистики'),
        ),
    ]
