# Generated by Django 5.1.4 on 2025-04-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0028_organization_stats_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='send_comments_to_amocrm',
            field=models.BooleanField(default=False, verbose_name='Комменты в amoCRM'),
        ),
    ]
