# Generated by Django 5.1.4 on 2025-04-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0029_organization_send_comments_to_amocrm'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingrequest',
            name='call_direction',
            field=models.CharField(choices=[('incoming', 'Входящий'), ('outgoing', 'Исходящий')], default='outgoing', max_length=10, verbose_name='Направление звонка'),
        ),
    ]
