# Generated by Django 5.1.4 on 2025-04-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0030_incomingrequest_call_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='minimal_call_length',
            field=models.IntegerField(default=30, verbose_name='Минимальная длительность звонка (сек)'),
        ),
    ]
