# Generated by Django 5.1.4 on 2025-04-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0031_organization_minimal_call_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='donkitrequest',
            name='raw_data',
            field=models.TextField(blank=True, null=True, verbose_name='Полный ответ нейросети'),
        ),
    ]
