# Generated by Django 5.1.4 on 2025-04-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0033_remove_criteriasteps_objections_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='comment_type',
            field=models.IntegerField(choices=[(1, 'Только аналитика'), (2, 'Только саммари'), (3, 'Аналитика и саммари')], default=3, verbose_name='Тип отправляемого комментария'),
        ),
        migrations.AddField(
            model_name='organization',
            name='summary_to_lead',
            field=models.BooleanField(default=False, verbose_name='Отправлять саммари в сделки'),
        ),
    ]
