# Generated by Django 5.1.4 on 2025-05-13 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0034_organization_comment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriasteps',
            name='criteria_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criteriasteps',
            name='criteria_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criteriasteps',
            name='criteria_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criteriasteps',
            name='criteria_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criteriasteps',
            name='criteria_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criteriasteps',
            name='criteria_6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criteriasteps',
            name='criteria_7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='show_dealstage_block',
            field=models.BooleanField(default=False, verbose_name='Показывать блок этапов сделок и возражений'),
        ),
        migrations.CreateModel(
            name='CriteriaLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_labels', to='zapp.organization')),
            ],
            options={
                'verbose_name': 'Наименование критерия',
                'verbose_name_plural': 'Наименование критериев',
                'ordering': ['organization', 'position'],
                'unique_together': {('organization', 'position')},
            },
        ),
    ]
