# Generated by Django 5.1.4 on 2025-05-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0036_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingrequest',
            name='ignored',
            field=models.BooleanField(default=False, verbose_name='Игнорирован'),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_criteria_score',
            field=models.IntegerField(default=10, verbose_name='Максимальная сумма оценок всех критериев'),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial_expires_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания триала'),
        ),
    ]
