# Generated by Django 5.1.4 on 2025-06-13 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0037_incomingrequest_ignored_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('request_ids', models.JSONField(default=list)),
                ('frequency', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsightExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('incoming_requests', models.ManyToManyField(related_name='insight_examples', to='zapp.incomingrequest')),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='zapp.weeklyinsight')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='zapp.organization')),
            ],
            options={
                'unique_together': {('organization', 'week_start')},
            },
        ),
        migrations.AddField(
            model_name='weeklyinsight',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='zapp.weeklyreport'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyinsight',
            unique_together={('report', 'title')},
        ),
    ]
