# Generated by Django 5.1.4 on 2025-06-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0038_weeklyinsight_insightexample_weeklyreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='custom_crm',
            field=models.BooleanField(default=False, verbose_name='Организация использует стороннюю CRM'),
        ),
    ]
