# Generated by Django 5.1.4 on 2025-07-04 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0039_organization_custom_crm'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('request_ids', models.JSONField(default=list)),
                ('frequency', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('request_ids', models.JSONField(default=list)),
                ('frequency', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('incoming_requests', models.ManyToManyField(related_name='error_examples', to='zapp.incomingrequest')),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='zapp.weeklyerror')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_error_reports', to='zapp.organization')),
            ],
            options={
                'unique_together': {('organization', 'week_start')},
            },
        ),
        migrations.AddField(
            model_name='weeklyerror',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='zapp.weeklyerrorreport'),
        ),
        migrations.CreateModel(
            name='FactorExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('incoming_requests', models.ManyToManyField(related_name='factor_examples', to='zapp.incomingrequest')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='zapp.weeklyfactor')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyFactorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_factor_reports', to='zapp.organization')),
            ],
            options={
                'unique_together': {('organization', 'week_start')},
            },
        ),
        migrations.AddField(
            model_name='weeklyfactor',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='zapp.weeklyfactorreport'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyerror',
            unique_together={('report', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklyfactor',
            unique_together={('report', 'title')},
        ),
    ]
