# Generated by Django 5.1.4 on 2025-11-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0040_weeklyerror_weeklyfactor_errorexample_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Суперадмин'), ('admin', 'Администратор организации'), ('user', 'Пользователь'), ('employee', 'сотрудник')], default='user', max_length=20),
        ),
    ]
